
### Ping
GET https://professional-network-jjossie-backend.onrender.com/user/
Accept: application/json

//****************************************
//* LOGIN/AUTH Endpoints
//****************************************/

### Register
POST https://professional-network-jjossie-backend.onrender.com/user/register
Content-Type: application/json

{
  "firstName": "Fluben",
  "lastName": "Gruber",
  "email": "flubengruber@yahoo.com",
  "password": "bruh"
}

### Login
POST https://professional-network-jjossie-backend.onrender.com/user/login
Content-Type: application/json

{
  "email": "Kirstin.Erdman@yahoo.com",
  "password": "bruh"
}

### Get Feed for User old
GET https://professional-network-jjossie-backend.vercel.app/user/63dbfc0d187fe1e57908cfea/feed
Accept: application/json


### get all users

GET https://professional-network-jjossie-backend.onrender.com/user/
Accept: application/json


### Get new feed
GET https://professional-network-jjossie-backend.onrender.com/user/feed
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc2NDQyMzUsImRhdGEiOnsidXNlcklkIjoiNjNmZDdlYjFhMTYzMGZkOTA4MjI1MDExIn0sImlhdCI6MTY3NzU1NzgzNX0.wmwHqz8YwzUgtkrkrhQAiByTLcIB72Q2T6VOleZhgj4

### Get new connection requests
GET https://professional-network-jjossie-backend.onrender.com/user/connectionRequests
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc2NDQyMzUsImRhdGEiOnsidXNlcklkIjoiNjNmZDdlYjFhMTYzMGZkOTA4MjI1MDExIn0sImlhdCI6MTY3NzU1NzgzNX0.wmwHqz8YwzUgtkrkrhQAiByTLcIB72Q2T6VOleZhgj4


### get all users
GET https://professional-network-jjossie-backend.onrender.com/user/
Accept: application/json
